// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package restapi

import (
	"github.com/andriystech/lgc/api/restapi/handlers"
	"github.com/andriystech/lgc/config"
	"github.com/andriystech/lgc/db/repositories"
	"github.com/andriystech/lgc/facilities/mongo"
	"github.com/andriystech/lgc/facilities/ws"
	"github.com/andriystech/lgc/services"
	"github.com/google/wire"
)

// Injectors from wire.go:

func InitializeHandlers(db mongo.ClientHelper) handlers.Handlers {
	serverConfig := config.GetServerConfig()
	usersCollection := mongo.NewUsersCollection(db, serverConfig)
	usersRepository := repositories.NewUsersRepository(usersCollection)
	userService := services.NewUserService(usersRepository)
	tokensRepository := repositories.NewTokensRepository(serverConfig)
	tokenService := services.NewTokenService(tokensRepository)
	userHandler := handlers.NewUserHandler(userService, tokenService)
	connectionsRepository := repositories.NewConnectionsRepository()
	messagesCollection := mongo.NewMessagesCollection(db, serverConfig)
	messagesRepository := repositories.NewMessagesRepository(messagesCollection)
	upgraderHelper := ws.NewUpgrader(serverConfig)
	webSocketService := services.NewWebSocketService(connectionsRepository, messagesRepository, usersRepository, upgraderHelper)
	chatHandler := handlers.NewChatHandler(tokenService, webSocketService)
	handlersHandlers := handlers.NewHandlers(userHandler, chatHandler)
	return handlersHandlers
}

// wire.go:

var collectionsSet = wire.NewSet(mongo.NewMessagesCollection, mongo.NewUsersCollection)

var repositoriesSet = wire.NewSet(repositories.NewConnectionsRepository, repositories.NewMessagesRepository, repositories.NewTokensRepository, repositories.NewUsersRepository)

var servicesSet = wire.NewSet(services.NewTokenService, services.NewUserService, services.NewWebSocketService)

var handlersSet = wire.NewSet(handlers.NewUserHandler, handlers.NewChatHandler)
