// Code generated by mockery v2.9.4. DO NOT EDIT.

package mocks

import (
	context "context"

	mongo "github.com/andriystech/lgc/facilities/mongo"
	mock "github.com/stretchr/testify/mock"
)

// ClientHelper is an autogenerated mock type for the ClientHelper type
type ClientHelper struct {
	mock.Mock
}

// Connect provides a mock function with given fields: _a0
func (_m *ClientHelper) Connect(_a0 context.Context) error {
	ret := _m.Called(_a0)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Database provides a mock function with given fields: _a0
func (_m *ClientHelper) Database(_a0 string) mongo.DatabaseHelper {
	ret := _m.Called(_a0)

	var r0 mongo.DatabaseHelper
	if rf, ok := ret.Get(0).(func(string) mongo.DatabaseHelper); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(mongo.DatabaseHelper)
		}
	}

	return r0
}

// Disconnect provides a mock function with given fields: _a0
func (_m *ClientHelper) Disconnect(_a0 context.Context) error {
	ret := _m.Called(_a0)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
