// Code generated by mockery v2.9.4. DO NOT EDIT.

package mocks

import (
	context "context"

	models "github.com/andriystech/lgc/models"
	mock "github.com/stretchr/testify/mock"

	ws "github.com/andriystech/lgc/facilities/ws"
)

// ConnectionsRepository is an autogenerated mock type for the ConnectionsRepository type
type ConnectionsRepository struct {
	mock.Mock
}

// AddConnection provides a mock function with given fields: _a0, _a1, _a2, _a3
func (_m *ConnectionsRepository) AddConnection(_a0 context.Context, _a1 string, _a2 ws.ConnHelper, _a3 *models.User) error {
	ret := _m.Called(_a0, _a1, _a2, _a3)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, ws.ConnHelper, *models.User) error); ok {
		r0 = rf(_a0, _a1, _a2, _a3)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ConnectedClients provides a mock function with given fields: _a0
func (_m *ConnectionsRepository) ConnectedClients(_a0 context.Context) ([]string, error) {
	ret := _m.Called(_a0)

	var r0 []string
	if rf, ok := ret.Get(0).(func(context.Context) []string); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CountConnections provides a mock function with given fields: _a0
func (_m *ConnectionsRepository) CountConnections(_a0 context.Context) (int, error) {
	ret := _m.Called(_a0)

	var r0 int
	if rf, ok := ret.Get(0).(func(context.Context) int); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Get(0).(int)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// DeleteConnection provides a mock function with given fields: _a0, _a1
func (_m *ConnectionsRepository) DeleteConnection(_a0 context.Context, _a1 string) error {
	ret := _m.Called(_a0, _a1)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetAllConnections provides a mock function with given fields: _a0
func (_m *ConnectionsRepository) GetAllConnections(_a0 context.Context) (map[string]ws.ConnHelper, error) {
	ret := _m.Called(_a0)

	var r0 map[string]ws.ConnHelper
	if rf, ok := ret.Get(0).(func(context.Context) map[string]ws.ConnHelper); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]ws.ConnHelper)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
