// Code generated by mockery v2.9.4. DO NOT EDIT.

package mocks

import (
	mongo "github.com/andriystech/lgc/facilities/mongo"
	mock "github.com/stretchr/testify/mock"
)

// DatabaseHelper is an autogenerated mock type for the DatabaseHelper type
type DatabaseHelper struct {
	mock.Mock
}

// Client provides a mock function with given fields:
func (_m *DatabaseHelper) Client() mongo.ClientHelper {
	ret := _m.Called()

	var r0 mongo.ClientHelper
	if rf, ok := ret.Get(0).(func() mongo.ClientHelper); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(mongo.ClientHelper)
		}
	}

	return r0
}

// Collection provides a mock function with given fields: name
func (_m *DatabaseHelper) Collection(name string) mongo.CollectionHelper {
	ret := _m.Called(name)

	var r0 mongo.CollectionHelper
	if rf, ok := ret.Get(0).(func(string) mongo.CollectionHelper); ok {
		r0 = rf(name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(mongo.CollectionHelper)
		}
	}

	return r0
}
