// Code generated by mockery v2.9.4. DO NOT EDIT.

package mocks

import (
	http "net/http"

	ws "github.com/andriystech/lgc/facilities/ws"
	mock "github.com/stretchr/testify/mock"
)

// UpgraderHelper is an autogenerated mock type for the UpgraderHelper type
type UpgraderHelper struct {
	mock.Mock
}

// Upgrade provides a mock function with given fields: _a0, _a1
func (_m *UpgraderHelper) Upgrade(_a0 http.ResponseWriter, _a1 *http.Request) (ws.ConnHelper, error) {
	ret := _m.Called(_a0, _a1)

	var r0 ws.ConnHelper
	if rf, ok := ret.Get(0).(func(http.ResponseWriter, *http.Request) ws.ConnHelper); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(ws.ConnHelper)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(http.ResponseWriter, *http.Request) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
