// Code generated by mockery v2.9.4. DO NOT EDIT.

package mocks

import (
	context "context"
	http "net/http"

	mock "github.com/stretchr/testify/mock"

	models "github.com/andriystech/lgc/models"

	ws "github.com/andriystech/lgc/facilities/ws"
)

// WebSocketService is an autogenerated mock type for the WebSocketService type
type WebSocketService struct {
	mock.Mock
}

// GetActiveConnectionsCount provides a mock function with given fields: _a0
func (_m *WebSocketService) GetActiveConnectionsCount(_a0 context.Context) (int, error) {
	ret := _m.Called(_a0)

	var r0 int
	if rf, ok := ret.Get(0).(func(context.Context) int); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Get(0).(int)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetActiveUsers provides a mock function with given fields: _a0
func (_m *WebSocketService) GetActiveUsers(_a0 context.Context) ([]string, error) {
	ret := _m.Called(_a0)

	var r0 []string
	if rf, ok := ret.Get(0).(func(context.Context) []string); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// LoadUserMessages provides a mock function with given fields: _a0, _a1, _a2
func (_m *WebSocketService) LoadUserMessages(_a0 context.Context, _a1 *models.User, _a2 ws.ConnHelper) error {
	ret := _m.Called(_a0, _a1, _a2)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *models.User, ws.ConnHelper) error); ok {
		r0 = rf(_a0, _a1, _a2)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewConnection provides a mock function with given fields: _a0, _a1, _a2
func (_m *WebSocketService) NewConnection(_a0 http.ResponseWriter, _a1 *http.Request, _a2 *models.User) error {
	ret := _m.Called(_a0, _a1, _a2)

	var r0 error
	if rf, ok := ret.Get(0).(func(http.ResponseWriter, *http.Request, *models.User) error); ok {
		r0 = rf(_a0, _a1, _a2)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// SaveUnreadMessages provides a mock function with given fields: _a0, _a1, _a2
func (_m *WebSocketService) SaveUnreadMessages(_a0 context.Context, _a1 *models.User, _a2 string) error {
	ret := _m.Called(_a0, _a1, _a2)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *models.User, string) error); ok {
		r0 = rf(_a0, _a1, _a2)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// SendMessageToAllConnections provides a mock function with given fields: _a0, _a1, _a2
func (_m *WebSocketService) SendMessageToAllConnections(_a0 context.Context, _a1 string, _a2 *models.User) error {
	ret := _m.Called(_a0, _a1, _a2)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, *models.User) error); ok {
		r0 = rf(_a0, _a1, _a2)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
